### ISSUE TITLE
[error] [docker-container-actions:Inspect container] TypeError: Cannot read property 'comand' of undefined

### ISSUE THREAD

**Issue by gregbert42** [naimo84/node-red-contrib-dockerode#26]
This had been working for awhile, but now I have this error when I try to inspect a container.

also:  [error] [docker-container-actions:7d64bf1b.df5b] Sytem Error:  [undefined] undefined when i try to restart a container

node-red-contrib-dockerode
0.4.21

inside docker: Docker version 20.10.8, build 3967b7d28e

docker-compose:

```
version: "2.2"
services:
  node-red:
    container_name: node-red
    restart: unless-stopped
    network_mode: host
    image: nodered/node-red:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/remote_fs_user/conf/node_red/data:/data
      - /home/remote_fs_user/conf/home-assistant/tensorflow:/tensorflow
    environment:
      - TZ="Europe/Zurich"
      - PROMETHEUS_COLLECT_DEFAULT_METRICS="true"
    user: 1000:1000
    group_add: [977]
    depends_on:
      - mosquitto
      - home-assistant

```

logs:
```

Welcome to Node-RED
===================

7 Oct 08:28:33 - [info] Node-RED version: v2.0.6
7 Oct 08:28:33 - [info] Node.js  version: v14.17.6
7 Oct 08:28:33 - [info] Linux 5.10.69-1-lts x64 LE
7 Oct 08:28:33 - [info] Loading palette nodes
7 Oct 08:28:35 - [info] Settings file  : /data/settings.js
7 Oct 08:28:35 - [info] Context store  : 'default' [module=memory]
7 Oct 08:28:35 - [info] User directory : /data
7 Oct 08:28:35 - [warn] Projects disabled : editorTheme.projects.enabled=false
7 Oct 08:28:35 - [info] Flows file     : /data/flows.json
7 Oct 08:28:35 - [info] Server now running at http://127.0.0.1:1880/
7 Oct 08:28:35 - [info] Starting flows
7 Oct 08:28:35 - [info] Instanciating PrometheusMetricConfigNode shield_source
7 Oct 08:28:35 - [info] Initializing Prometheus exporter
7 Oct 08:28:35 - [info] Prometheus metrics are available at path /metrics
7 Oct 08:28:35 - [info] PrometheusMetricConfigNode.registerMetric shield_source
7 Oct 08:28:35 - [info] Added Prometheus Counter shield_source
7 Oct 08:28:35 - [info] Instanciating PrometheusExporterNode 8fd3c501.be3b28
7 Oct 08:28:35 - [info] Started flows
7 Oct 08:28:35 - [info] [tcp in:cf78a798ea8a2924] listening on port 1113
7 Oct 08:28:35 - [info] [server:Home Assistant] Connecting to http://192.168.2.24:8123
7 Oct 08:28:35 - [info] [mqtt-broker:Fractal] Connected to broker: Node-red@mqtt://192.168.2.24:1883
7 Oct 08:28:35 - [info] [server:Home Assistant] Connected to http://192.168.2.24:8123
7 Oct 08:28:55 - [error] [docker-container-actions:Inspect container] TypeError: Cannot read property 'comand' of undefined
(node:17) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
    at /data/node_modules/node-red-contrib-dockerode/dist/docker-container-actions.js:701:50
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
7 Oct 08:35:22 - [info] Stopping flows
7 Oct 08:35:22 - [info] [tcp in:cf78a798ea8a2924] stopped listening on port
7 Oct 08:35:22 - [info] [server:Home Assistant] Closing connection to http://192.168.2.24:8123
7 Oct 08:35:22 - [info] Closing PrometheusMetricConfigNode shield_source
7 Oct 08:35:22 - [info] Removed Prometheus metric shield_source
7 Oct 08:35:22 - [info] AlexaLocalNode closing done...
7 Oct 08:35:22 - [info] [mqtt-broker:Fractal] Disconnected from broker: Node-red@mqtt://192.168.2.24:1883
7 Oct 08:35:22 - [info] Stopped flows
7 Oct 08:35:22 - [info] Starting flows
7 Oct 08:35:22 - [info] Instanciating PrometheusMetricConfigNode shield_source
7 Oct 08:35:22 - [info] PrometheusMetricConfigNode.registerMetric shield_source
7 Oct 08:35:22 - [info] Added Prometheus Counter shield_source
7 Oct 08:35:22 - [info] Instanciating PrometheusExporterNode 8fd3c501.be3b28
7 Oct 08:35:22 - [info] Started flows
7 Oct 08:35:22 - [info] [tcp in:cf78a798ea8a2924] listening on port 1113
7 Oct 08:35:22 - [info] [server:Home Assistant] Connecting to http://192.168.2.24:8123
7 Oct 08:35:22 - [info] [mqtt-broker:Fractal] Connected to broker: Node-red@mqtt://192.168.2.24:1883
7 Oct 08:35:22 - [info] [server:Home Assistant] Connected to http://192.168.2.24:8123
7 Oct 08:35:24 - [error] [docker-container-actions:Inspect container] TypeError: Cannot read property 'comand' of undefined
7 Oct 08:35:27 - [error] [docker-container-actions:Inspect container] TypeError: Cannot read property 'comand' of undefined
7 Oct 08:36:07 - [error] [docker-container-actions:Inspect container] TypeError: Cannot read property 'comand' of undefined


```
